### ISSUE TITLE
Simplify Error Reporting

### ISSUE THREAD

**Issue by wrenger** [nwrenger/schiller-db#1]
https://github.com/nwrenger/sndm/blob/927732e4d9eb5e020109e51476f5939467c386de/src/server.rs#L47

The unauthorized error could be simpler, just having no string field. Then this whole distinction between having no key and having a wrong one could be left out and just „Unauthorized“.

**Comment by nwrenger** [comment]
fixed in [this commit](https://github.com/nwrenger/sndm/commit/d2d219368307066adb3976d66ab549739eb47798) and in [this commit](https://github.com/nwrenger/sndm/commit/c2dd27167add622b71d1466aedd659b948f813ca).

**Comment by nwrenger** [comment]
[also here](https://github.com/nwrenger/sndm/commit/9be191499fa07db56259d68b315fdbc8d03d566e)
