### ISSUE TITLE
Don’t put keys into your source code 

### ISSUE THREAD

**Issue by wrenger** [nwrenger/schiller-db#2]
https://github.com/nwrenger/sndm/blob/927732e4d9eb5e020109e51476f5939467c386de/src/server.rs#LL46C30-L46C30

Just use const variables with ` env! `:

```rs
const KEY_A: &str = env!("SNDM_KEY_A");
```

**Comment by nwrenger** [comment]
fixed in [this commit](https://github.com/nwrenger/sndm/commit/98bbda7ab242eba8c555c93de4c30cc8e76ba451) and in [this commit](https://github.com/nwrenger/sndm/commit/c2dd27167add622b71d1466aedd659b948f813ca).
